package entity;

public enum HospitalEnum {
    ACIBADEM_HASTANESI(),
    MEDICANA_SAGLIK_GRUBU(),
    AMERIKAN_HASTANESI,
    KOC_UNIVERSITESI_HASTANESI,
    LIV_HOSPITAL,
    BASKENT_UNIVERSITESI_HASTANESI,
    ISTANBUL_UNIVERSITESI_CERRAHPASA,
    KARTAL_KOZYATAGI_DEVLET_HASTANESI,
    ATATURK_EGITIM_VE_ARASTIRMA_HASTANESI,
    CAPA_TIP_FAKULTESI_HASTANESI


}
